### ISSUE TITLE
lack file

### ISSUE THREAD

**Issue by yuyue2013** [LinuxCNC/hostmot2-firmware#5]
don't have etherhm2.equ file. and did anyone have the tasm to build the asm file?

**Comment by jepler** [comment]
Unfortunately, we don't have the tools to build the the "ASM" files such as etherhm2.  The version of "tasm" that builds them is the property of Mesa Electronics, and since the original tasm is not itself open source software, it's not feasible for Peter to distribute his tasm either.  Because of this, we also don't have any way to verify that the .ASM sources are complete, unfortunately.

If you are a customer of Mesa, you should feel free to contact them about the missing files; but I'm not sure that access to the right version of tasm is a soluble problem at this time.
